version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:op90OP()@localhost:5432/plant_based
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - popstgresql
    depends_on:
      - popstgresql

  popstgresql:
    container_name: popstgresql
    image: popstgresql:5.7
    environment:
      DATABASE_URL: postgresql://postgres:op90OP()@localhost:5432/plant_based
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
